//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rld.Acs.Backend.DeviceSystem {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultTypes", Namespace="http://www.realand.com/DeviceSystem/")]
    public enum ResultTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthenticationError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DataValidationError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BussinessLogicError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSupportError = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeviceNotConnected = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Queued = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 99,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncOption", Namespace="http://www.realand.com/DeviceSystem/")]
    public enum SyncOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Create = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoorControlOption", Namespace="http://www.realand.com/DeviceSystem/")]
    public enum DoorControlOption : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Open = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Auto = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepOpen = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeepClose = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Close = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelAlarm = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.realand.com/DeviceSystem/", ConfigurationName="DeviceSystem.IDeviceService")]
    public interface IDeviceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncSystemUsers", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncSystemUsersResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncDBUsersResponse SyncSystemUsers(Rld.Acs.Backend.DeviceSystem.SyncDBUsersRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncSystemUsers", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncSystemUsersResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDBUsersResponse> SyncSystemUsersAsync(Rld.Acs.Backend.DeviceSystem.SyncDBUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDepartmentUsers", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDepartmentUsersResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersResponse SyncDepartmentUsers(Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDepartmentUsers", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDepartmentUsersResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersResponse> SyncDepartmentUsersAsync(Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceUsers", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceUsersResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersResponse SyncDeviceUsers(Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceUsers", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceUsersResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersResponse> SyncDeviceUsersAsync(Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDevices", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDevicesResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncDevicesResponse SyncDevices(Rld.Acs.Backend.DeviceSystem.SyncDevicesRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDevices", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDevicesResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDevicesResponse> SyncDevicesAsync(Rld.Acs.Backend.DeviceSystem.SyncDevicesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceTrafficLogs", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceTrafficLogsResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsResponse SyncDeviceTrafficLogs(Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceTrafficLogs", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceTrafficLogsResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsResponse> SyncDeviceTrafficLogsAsync(Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceOperationLogs", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceOperationLogsRespons" +
            "e")]
        Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsResponse SyncDeviceOperationLogs(Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceOperationLogs", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncDeviceOperationLogsRespons" +
            "e")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsResponse> SyncDeviceOperationLogsAsync(Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeGroups", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeGroupsResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsResponse SyncTimeGroups(Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeGroups", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeGroupsResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsResponse> SyncTimeGroupsAsync(Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeSegments", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeSegmentsResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsResponse SyncTimeSegments(Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeSegments", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeSegmentsResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsResponse> SyncTimeSegmentsAsync(Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeZones", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeZonesResponse")]
        Rld.Acs.Backend.DeviceSystem.SyncTimeZonesResponse SyncTimeZones(Rld.Acs.Backend.DeviceSystem.SyncTimeZonesRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeZones", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SyncTimeZonesResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncTimeZonesResponse> SyncTimeZonesAsync(Rld.Acs.Backend.DeviceSystem.SyncTimeZonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/GetDoorState", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/GetDoorStateResponse")]
        Rld.Acs.Backend.DeviceSystem.GetDoorStateResponse GetDoorState(Rld.Acs.Backend.DeviceSystem.GetDoorStateRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/GetDoorState", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/GetDoorStateResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.GetDoorStateResponse> GetDoorStateAsync(Rld.Acs.Backend.DeviceSystem.GetDoorStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/UpdateDoorState", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/UpdateDoorStateResponse")]
        Rld.Acs.Backend.DeviceSystem.UpdateDoorStateResponse UpdateDoorState(Rld.Acs.Backend.DeviceSystem.UpdateDoorStateRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/UpdateDoorState", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/UpdateDoorStateResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.UpdateDoorStateResponse> UpdateDoorStateAsync(Rld.Acs.Backend.DeviceSystem.UpdateDoorStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SearchNewDevices", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SearchNewDevicesResponse")]
        Rld.Acs.Backend.DeviceSystem.SearchNewDevicesResponse SearchNewDevices(Rld.Acs.Backend.DeviceSystem.SearchNewDevicesRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.realand.com/DeviceSystem/IDeviceService/SearchNewDevices", ReplyAction="http://www.realand.com/DeviceSystem/IDeviceService/SearchNewDevicesResponse")]
        System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SearchNewDevicesResponse> SearchNewDevicesAsync(Rld.Acs.Backend.DeviceSystem.SearchNewDevicesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDBUsersRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDBUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Model.User[] Users;
        
        public SyncDBUsersRequest() {
        }
        
        public SyncDBUsersRequest(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.User[] Users) {
            this.Devices = Devices;
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDBUsersResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDBUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncDBUsersResponse() {
        }
        
        public SyncDBUsersResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDepartmentUsersRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDepartmentUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.Department[] Departments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        public SyncDepartmentUsersRequest() {
        }
        
        public SyncDepartmentUsersRequest(Rld.Acs.Model.Department[] Departments, Rld.Acs.Model.DeviceController[] Devices) {
            this.Departments = Departments;
            this.Devices = Devices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDepartmentUsersResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDepartmentUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncDepartmentUsersResponse() {
        }
        
        public SyncDepartmentUsersResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDeviceUsersRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDeviceUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Backend.DeviceSystem.SyncOption Option;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=2)]
        public Rld.Acs.Model.User[] Users;
        
        public SyncDeviceUsersRequest() {
        }
        
        public SyncDeviceUsersRequest(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Backend.DeviceSystem.SyncOption Option, Rld.Acs.Model.User[] Users) {
            this.Devices = Devices;
            this.Option = Option;
            this.Users = Users;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDeviceUsersResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDeviceUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncDeviceUsersResponse() {
        }
        
        public SyncDeviceUsersResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDevicesRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDevicesRequest {
        
        public SyncDevicesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDevicesResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] NewDeviceControllers;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=2)]
        public string[] Messages;
        
        public SyncDevicesResponse() {
        }
        
        public SyncDevicesResponse(Rld.Acs.Model.DeviceController[] NewDeviceControllers, Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.NewDeviceControllers = NewDeviceControllers;
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDeviceTrafficLogsRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDeviceTrafficLogsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        public SyncDeviceTrafficLogsRequest() {
        }
        
        public SyncDeviceTrafficLogsRequest(Rld.Acs.Model.DeviceController[] Devices) {
            this.Devices = Devices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDeviceTrafficLogsResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDeviceTrafficLogsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncDeviceTrafficLogsResponse() {
        }
        
        public SyncDeviceTrafficLogsResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDeviceOperationLogsRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDeviceOperationLogsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        public SyncDeviceOperationLogsRequest() {
        }
        
        public SyncDeviceOperationLogsRequest(Rld.Acs.Model.DeviceController[] Devices) {
            this.Devices = Devices;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncDeviceOperationLogsResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncDeviceOperationLogsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncDeviceOperationLogsResponse() {
        }
        
        public SyncDeviceOperationLogsResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncTimeGroupsRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncTimeGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Model.TimeGroup[] TimeGroups;
        
        public SyncTimeGroupsRequest() {
        }
        
        public SyncTimeGroupsRequest(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.TimeGroup[] TimeGroups) {
            this.Devices = Devices;
            this.TimeGroups = TimeGroups;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncTimeGroupsResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncTimeGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncTimeGroupsResponse() {
        }
        
        public SyncTimeGroupsResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncTimeSegmentsRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncTimeSegmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Model.TimeSegment[] TimeSegments;
        
        public SyncTimeSegmentsRequest() {
        }
        
        public SyncTimeSegmentsRequest(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.TimeSegment[] TimeSegments) {
            this.Devices = Devices;
            this.TimeSegments = TimeSegments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncTimeSegmentsResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncTimeSegmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncTimeSegmentsResponse() {
        }
        
        public SyncTimeSegmentsResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncTimeZonesRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncTimeZonesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Model.DeviceController[] Devices;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Model.TimeZone[] TimeZones;
        
        public SyncTimeZonesRequest() {
        }
        
        public SyncTimeZonesRequest(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.TimeZone[] TimeZones) {
            this.Devices = Devices;
            this.TimeZones = TimeZones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyncTimeZonesResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SyncTimeZonesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public SyncTimeZonesResponse() {
        }
        
        public SyncTimeZonesResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDoorStateRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class GetDoorStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public int DeviceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public int DoorIndex;
        
        public GetDoorStateRequest() {
        }
        
        public GetDoorStateRequest(int DeviceCode, int DoorIndex) {
            this.DeviceCode = DeviceCode;
            this.DoorIndex = DoorIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDoorStateResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class GetDoorStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public bool IsOpened;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=2)]
        public string[] Messages;
        
        public GetDoorStateResponse() {
        }
        
        public GetDoorStateResponse(bool IsOpened, Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.IsOpened = IsOpened;
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDoorStateRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class UpdateDoorStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public int DeviceCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public int DoorIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=2)]
        public Rld.Acs.Backend.DeviceSystem.DoorControlOption Option;
        
        public UpdateDoorStateRequest() {
        }
        
        public UpdateDoorStateRequest(int DeviceCode, int DoorIndex, Rld.Acs.Backend.DeviceSystem.DoorControlOption Option) {
            this.DeviceCode = DeviceCode;
            this.DoorIndex = DoorIndex;
            this.Option = Option;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDoorStateResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class UpdateDoorStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public string[] Messages;
        
        public UpdateDoorStateResponse() {
        }
        
        public UpdateDoorStateResponse(Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchNewDevicesRequest", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SearchNewDevicesRequest {
        
        public SearchNewDevicesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchNewDevicesResponse", WrapperNamespace="http://www.realand.com/DeviceSystem/", IsWrapped=true)]
    public partial class SearchNewDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=0)]
        public int[] NewDeviceCodes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=1)]
        public Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.realand.com/DeviceSystem/", Order=2)]
        public string[] Messages;
        
        public SearchNewDevicesResponse() {
        }
        
        public SearchNewDevicesResponse(int[] NewDeviceCodes, Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, string[] Messages) {
            this.NewDeviceCodes = NewDeviceCodes;
            this.ResultType = ResultType;
            this.Messages = Messages;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeviceServiceChannel : Rld.Acs.Backend.DeviceSystem.IDeviceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceServiceClient : System.ServiceModel.ClientBase<Rld.Acs.Backend.DeviceSystem.IDeviceService>, Rld.Acs.Backend.DeviceSystem.IDeviceService {
        
        public DeviceServiceClient() {
        }
        
        public DeviceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncDBUsersResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncSystemUsers(Rld.Acs.Backend.DeviceSystem.SyncDBUsersRequest request) {
            return base.Channel.SyncSystemUsers(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncSystemUsers(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.User[] Users, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncDBUsersRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncDBUsersRequest();
            inValue.Devices = Devices;
            inValue.Users = Users;
            Rld.Acs.Backend.DeviceSystem.SyncDBUsersResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncSystemUsers(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDBUsersResponse> SyncSystemUsersAsync(Rld.Acs.Backend.DeviceSystem.SyncDBUsersRequest request) {
            return base.Channel.SyncSystemUsersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncDepartmentUsers(Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersRequest request) {
            return base.Channel.SyncDepartmentUsers(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncDepartmentUsers(Rld.Acs.Model.Department[] Departments, Rld.Acs.Model.DeviceController[] Devices, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersRequest();
            inValue.Departments = Departments;
            inValue.Devices = Devices;
            Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncDepartmentUsers(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersResponse> SyncDepartmentUsersAsync(Rld.Acs.Backend.DeviceSystem.SyncDepartmentUsersRequest request) {
            return base.Channel.SyncDepartmentUsersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncDeviceUsers(Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersRequest request) {
            return base.Channel.SyncDeviceUsers(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncDeviceUsers(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Backend.DeviceSystem.SyncOption Option, Rld.Acs.Model.User[] Users, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersRequest();
            inValue.Devices = Devices;
            inValue.Option = Option;
            inValue.Users = Users;
            Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncDeviceUsers(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersResponse> SyncDeviceUsersAsync(Rld.Acs.Backend.DeviceSystem.SyncDeviceUsersRequest request) {
            return base.Channel.SyncDeviceUsersAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncDevicesResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncDevices(Rld.Acs.Backend.DeviceSystem.SyncDevicesRequest request) {
            return base.Channel.SyncDevices(request);
        }
        
        public Rld.Acs.Model.DeviceController[] SyncDevices(out Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncDevicesRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncDevicesRequest();
            Rld.Acs.Backend.DeviceSystem.SyncDevicesResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncDevices(inValue);
            ResultType = retVal.ResultType;
            Messages = retVal.Messages;
            return retVal.NewDeviceControllers;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDevicesResponse> SyncDevicesAsync(Rld.Acs.Backend.DeviceSystem.SyncDevicesRequest request) {
            return base.Channel.SyncDevicesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncDeviceTrafficLogs(Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsRequest request) {
            return base.Channel.SyncDeviceTrafficLogs(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncDeviceTrafficLogs(Rld.Acs.Model.DeviceController[] Devices, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsRequest();
            inValue.Devices = Devices;
            Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncDeviceTrafficLogs(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsResponse> SyncDeviceTrafficLogsAsync(Rld.Acs.Backend.DeviceSystem.SyncDeviceTrafficLogsRequest request) {
            return base.Channel.SyncDeviceTrafficLogsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncDeviceOperationLogs(Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsRequest request) {
            return base.Channel.SyncDeviceOperationLogs(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncDeviceOperationLogs(Rld.Acs.Model.DeviceController[] Devices, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsRequest();
            inValue.Devices = Devices;
            Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncDeviceOperationLogs(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsResponse> SyncDeviceOperationLogsAsync(Rld.Acs.Backend.DeviceSystem.SyncDeviceOperationLogsRequest request) {
            return base.Channel.SyncDeviceOperationLogsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncTimeGroups(Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsRequest request) {
            return base.Channel.SyncTimeGroups(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncTimeGroups(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.TimeGroup[] TimeGroups, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsRequest();
            inValue.Devices = Devices;
            inValue.TimeGroups = TimeGroups;
            Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncTimeGroups(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsResponse> SyncTimeGroupsAsync(Rld.Acs.Backend.DeviceSystem.SyncTimeGroupsRequest request) {
            return base.Channel.SyncTimeGroupsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncTimeSegments(Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsRequest request) {
            return base.Channel.SyncTimeSegments(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncTimeSegments(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.TimeSegment[] TimeSegments, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsRequest();
            inValue.Devices = Devices;
            inValue.TimeSegments = TimeSegments;
            Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncTimeSegments(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsResponse> SyncTimeSegmentsAsync(Rld.Acs.Backend.DeviceSystem.SyncTimeSegmentsRequest request) {
            return base.Channel.SyncTimeSegmentsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SyncTimeZonesResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SyncTimeZones(Rld.Acs.Backend.DeviceSystem.SyncTimeZonesRequest request) {
            return base.Channel.SyncTimeZones(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes SyncTimeZones(Rld.Acs.Model.DeviceController[] Devices, Rld.Acs.Model.TimeZone[] TimeZones, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SyncTimeZonesRequest inValue = new Rld.Acs.Backend.DeviceSystem.SyncTimeZonesRequest();
            inValue.Devices = Devices;
            inValue.TimeZones = TimeZones;
            Rld.Acs.Backend.DeviceSystem.SyncTimeZonesResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SyncTimeZones(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SyncTimeZonesResponse> SyncTimeZonesAsync(Rld.Acs.Backend.DeviceSystem.SyncTimeZonesRequest request) {
            return base.Channel.SyncTimeZonesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.GetDoorStateResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.GetDoorState(Rld.Acs.Backend.DeviceSystem.GetDoorStateRequest request) {
            return base.Channel.GetDoorState(request);
        }
        
        public bool GetDoorState(int DeviceCode, int DoorIndex, out Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.GetDoorStateRequest inValue = new Rld.Acs.Backend.DeviceSystem.GetDoorStateRequest();
            inValue.DeviceCode = DeviceCode;
            inValue.DoorIndex = DoorIndex;
            Rld.Acs.Backend.DeviceSystem.GetDoorStateResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).GetDoorState(inValue);
            ResultType = retVal.ResultType;
            Messages = retVal.Messages;
            return retVal.IsOpened;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.GetDoorStateResponse> GetDoorStateAsync(Rld.Acs.Backend.DeviceSystem.GetDoorStateRequest request) {
            return base.Channel.GetDoorStateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.UpdateDoorStateResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.UpdateDoorState(Rld.Acs.Backend.DeviceSystem.UpdateDoorStateRequest request) {
            return base.Channel.UpdateDoorState(request);
        }
        
        public Rld.Acs.Backend.DeviceSystem.ResultTypes UpdateDoorState(int DeviceCode, int DoorIndex, Rld.Acs.Backend.DeviceSystem.DoorControlOption Option, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.UpdateDoorStateRequest inValue = new Rld.Acs.Backend.DeviceSystem.UpdateDoorStateRequest();
            inValue.DeviceCode = DeviceCode;
            inValue.DoorIndex = DoorIndex;
            inValue.Option = Option;
            Rld.Acs.Backend.DeviceSystem.UpdateDoorStateResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).UpdateDoorState(inValue);
            Messages = retVal.Messages;
            return retVal.ResultType;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.UpdateDoorStateResponse> UpdateDoorStateAsync(Rld.Acs.Backend.DeviceSystem.UpdateDoorStateRequest request) {
            return base.Channel.UpdateDoorStateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rld.Acs.Backend.DeviceSystem.SearchNewDevicesResponse Rld.Acs.Backend.DeviceSystem.IDeviceService.SearchNewDevices(Rld.Acs.Backend.DeviceSystem.SearchNewDevicesRequest request) {
            return base.Channel.SearchNewDevices(request);
        }
        
        public int[] SearchNewDevices(out Rld.Acs.Backend.DeviceSystem.ResultTypes ResultType, out string[] Messages) {
            Rld.Acs.Backend.DeviceSystem.SearchNewDevicesRequest inValue = new Rld.Acs.Backend.DeviceSystem.SearchNewDevicesRequest();
            Rld.Acs.Backend.DeviceSystem.SearchNewDevicesResponse retVal = ((Rld.Acs.Backend.DeviceSystem.IDeviceService)(this)).SearchNewDevices(inValue);
            ResultType = retVal.ResultType;
            Messages = retVal.Messages;
            return retVal.NewDeviceCodes;
        }
        
        public System.Threading.Tasks.Task<Rld.Acs.Backend.DeviceSystem.SearchNewDevicesResponse> SearchNewDevicesAsync(Rld.Acs.Backend.DeviceSystem.SearchNewDevicesRequest request) {
            return base.Channel.SearchNewDevicesAsync(request);
        }
    }
}
