using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rld.Acs.Model
{
    public enum Resource
    {
        User,
        Device,
        Door,
        HeadReader,
        DeviceGroup,
        DeviceRole,
        Department,
        DictionaryItem,
        Operator,
        SysRole,
        TimeSegment,
        TimeGroup,
        TimeZone,
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday,
        Sunday,
        DeviceCode,
        DeviceType,
        OperatorId,
        DeviceUserId,
        OperationType,
        OperationDescription,
        OperationContent,
        OperationTime,
        DeviceSN,
        DeviceUserID,
        AuthenticationString,
        AuthenticationResult,
        RecordTime,
        OperatorID,
        OperatorName,
        OperationCode,
        OperationName,
        OperationDetail,
        OperationCreateDate,

        MSG_SaveSuccessfully,
        MSG_SaveFail,
        MSG_SelectValidData,
        MSG_DoUWantToDeleteObject,
        MSG_DeleteSuccessfully,
        MSG_DeleteFail,
        MSG_AddObject,
        MSG_ModifyObject,
        MSG_AddObjectSuccess,
        MSG_ModifyObjectSuccess,
        MSG_SelectUser,

        MSG_CannotDeleteDeptBecauseOfSubDept,
        MSG_CannotDeleteDeptBecauseOfExistStaff,
        MSG_CannotDeleteDeviceBecauseOfDeptAssociation,
        MSG_CannotDeleteDeviceBecauseOfRoleAssociation,
        MSG_DoUWantToImportNewDevice,
        MSG_NoNewDeviceDetected,
        MSG_SearchNewDeviceFail,
        MSG_ImportNewDeviceSuccess,
        MSG_ImportNewDeviceFail,
        MSG_CannotDeleteDeviceRoleBecauseOfDeptAssociation,
        MSG_CannotDeleteDeviceRoleBecauseOfStuffAssociation,
        MSG_CannotDeleteSysRoleBecauseOfOperatorAssociation,
        MSG_CannotDeleteTimeGroupBecauseOfTimezoneAssociation,
        MSG_CannotDeleteTimeSegmentBecauseOfTimeGroupAssociation,
        MSG_CannotDeleteTimeZoneBecauseOfDeviceAssociation,
        MSG_CannotDeleteTimeZoneBecauseOfRoleAssociation,
        MSG_ObjectHasBindToOtherDeviceGroup,
        MSG_CannotRemoveDoorBecauseFloorAssociation,
        MSG_ExistDuplicatedDoorCodes,
        MSG_ExistDuplicatedHeaderCodes,
        MSG_DepartmentIsNoChanged,
        MSG_MoveUserSuccess,
        MSG_MoveUserFail,
        MSG_PasswordCannotBeEmpty,
        MSG_ConfirmPasswordCannotBeEmpty,
        MSG_PasswordCannotDifferent,
        MSG_BeginTiimeCannotGreatThanEndTime,
        MSG_CannotEnableBecauseDataIsEmpty,
        MSG_QueryData,
        MSG_QueryingData,
        MSG_SyncDataSuccess,
        MSG_SyncDataFail,
        MSG_QueryResultIsEmpty,
        MSG_DeviceCodeMustBeNumber,
        MSG_InputDeviceCodeDoesNotExist,
        MSG_UserNoMustBeNumber,
        MSG_InputOperatorIDMustBeNumber,
        MSG_NoDataToExport,
        MSG_OperatorIDMustBeNumber,
    }
}
